# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
    adapter: mysql
    database: shp_development
    user: root
    password: Shp01
    host: localhost
    encoding: utf8

development:
    adapter: mysql
    database: shp_production
    user: root
    password: Shp01
    host: localhost
    encoding: utf8
